# https://help.github.com/ja/articles/metadata-syntax-for-github-actions
name: Download Annotations Action

description: GitHub actions to download annotations.

author: technote-space

inputs:
  GITHUB_TOKEN:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: true
  TARGET_RUN_ID:
    description: Target run id
    default: ${{ github.run_id }}
    required: true
  WORKSPACE:
    description: workspace
    default: ${{ github.workspace }}
    required: true
  FILENAME:
    description: result filename
    default: annotations.json
    required: false
  RESULT_FILENAME:
    description: result filename
    default: result.json
    required: false

  INCLUDE_JOB_NAME_PATTERNS:
    description: Include job name patterns.
    required: false
  INCLUDE_JOB_NAME_PATTERN_FLAGS:
    description: Include job name pattern flags.
    required: false
  EXCLUDE_JOB_NAME_PATTERNS:
    description: Exclude job name patterns.
    required: false
  EXCLUDE_JOB_NAME_PATTERN_FLAGS:
    description: Exclude job name pattern flags.
    required: false

  INCLUDE_LEVELS:
    description: Include levels (notice, warning, or failure).
    required: false
  EXCLUDE_LEVELS:
    description: Exclude levels (notice, warning, or failure).
    required: false

  INCLUDE_MESSAGE_PATTERNS:
    description: Include message patterns.
    required: false
  INCLUDE_MESSAGE_PATTERN_FLAGS:
    description: Include message pattern flags.
    required: false
  EXCLUDE_MESSAGE_PATTERNS:
    description: Exclude message patterns.
    required: false
  EXCLUDE_MESSAGE_PATTERN_FLAGS:
    description: Exclude message pattern flags.
    required: false

outputs:
  number:
    description: number of annotations
  messages:
    description: messages of annotations
  path:
    description: annotations file path
  result_path:
    description: result file path

branding:
  # https://feathericons.com/
  icon: 'download'
  color: 'blue'

runs:
  using: node16
  main: lib/main.js
