"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getExcludeMessagePatternFlags = exports.getIncludeMessagePatternFlags = exports.getExcludeMessagePatterns = exports.getIncludeMessagePatterns = exports.getExcludeLevels = exports.getIncludeLevels = exports.getExcludeJobNamePatternFlags = exports.getIncludeJobNamePatternFlags = exports.getExcludeJobNamePatterns = exports.getIncludeJobNamePatterns = exports.getResultFilename = exports.getFilename = exports.getWorkspace = exports.getTargetRunId = void 0;
const core_1 = require("@actions/core");
const github_action_helper_1 = require("@technote-space/github-action-helper");
const getTargetRunId = (context) => /^\d+$/.test((0, core_1.getInput)('TARGET_RUN_ID')) ? Number((0, core_1.getInput)('TARGET_RUN_ID')) : context.runId;
exports.getTargetRunId = getTargetRunId;
const getWorkspace = () => (0, core_1.getInput)('WORKSPACE');
exports.getWorkspace = getWorkspace;
const getFilename = () => (0, core_1.getInput)('FILENAME');
exports.getFilename = getFilename;
const getResultFilename = () => (0, core_1.getInput)('RESULT_FILENAME');
exports.getResultFilename = getResultFilename;
const getIncludeJobNamePatterns = () => github_action_helper_1.Utils.getArrayInput('INCLUDE_JOB_NAME_PATTERNS');
exports.getIncludeJobNamePatterns = getIncludeJobNamePatterns;
const getExcludeJobNamePatterns = () => github_action_helper_1.Utils.getArrayInput('EXCLUDE_JOB_NAME_PATTERNS');
exports.getExcludeJobNamePatterns = getExcludeJobNamePatterns;
const getIncludeJobNamePatternFlags = () => (0, core_1.getInput)('INCLUDE_JOB_NAME_PATTERN_FLAGS');
exports.getIncludeJobNamePatternFlags = getIncludeJobNamePatternFlags;
const getExcludeJobNamePatternFlags = () => (0, core_1.getInput)('EXCLUDE_JOB_NAME_PATTERN_FLAGS');
exports.getExcludeJobNamePatternFlags = getExcludeJobNamePatternFlags;
const getIncludeLevels = () => github_action_helper_1.Utils.getArrayInput('INCLUDE_LEVELS');
exports.getIncludeLevels = getIncludeLevels;
const getExcludeLevels = () => github_action_helper_1.Utils.getArrayInput('EXCLUDE_LEVELS');
exports.getExcludeLevels = getExcludeLevels;
const getIncludeMessagePatterns = () => github_action_helper_1.Utils.getArrayInput('INCLUDE_MESSAGE_PATTERNS');
exports.getIncludeMessagePatterns = getIncludeMessagePatterns;
const getExcludeMessagePatterns = () => github_action_helper_1.Utils.getArrayInput('EXCLUDE_MESSAGE_PATTERNS');
exports.getExcludeMessagePatterns = getExcludeMessagePatterns;
const getIncludeMessagePatternFlags = () => (0, core_1.getInput)('INCLUDE_MESSAGE_PATTERN_FLAGS');
exports.getIncludeMessagePatternFlags = getIncludeMessagePatternFlags;
const getExcludeMessagePatternFlags = () => (0, core_1.getInput)('EXCLUDE_MESSAGE_PATTERN_FLAGS');
exports.getExcludeMessagePatternFlags = getExcludeMessagePatternFlags;
